### PR TITLE
Fixed compilation with GHC 7.8.4

### LINKED ISSUE #6: Broken compilation with GHC 7.8.4
```
$ ghc -V
ghc -V
The Glorious Glasgow Haskell Compilation System, version 7.8.4
```

```
$ cabal get STMonadTrans-0.4
$ cd STMonadTrans-0.4
$ cabal install
Control/Monad/ST/Trans/Internal.hs:126:21:
    Could not deduce (Applicative m) arising from a use of ‘liftST’
    from the context (Monad (STT s m), Monad m)
      bound by the instance declaration
      at Control/Monad/ST/Trans/Internal.hs:124:10-50
    or from (Ix i)
      bound by the type signature for
                 getBounds :: Ix i => STArray s i e -> STT s m (i, i)
      at Control/Monad/ST/Trans/Internal.hs:126:5-13
    Possible fix:
      add (Applicative m) to the context of
        the type signature for
          getBounds :: Ix i => STArray s i e -> STT s m (i, i)
        or the instance declaration
    In the expression: liftST (getBounds arr)
    In an equation for ‘getBounds’:
        getBounds arr = liftST (getBounds arr)
    In the instance declaration for ‘MArray (STArray s) e (STT s m)’

Control/Monad/ST/Trans/Internal.hs:128:26:
    Could not deduce (Applicative m) arising from a use of ‘liftST’
    from the context (Monad (STT s m), Monad m)
      bound by the instance declaration
      at Control/Monad/ST/Trans/Internal.hs:124:10-50
    or from (Ix i)
      bound by the type signature for
                 getNumElements :: Ix i => STArray s i e -> STT s m Int
      at Control/Monad/ST/Trans/Internal.hs:128:5-18
    Possible fix:
      add (Applicative m) to the context of
        the type signature for
          getNumElements :: Ix i => STArray s i e -> STT s m Int
        or the instance declaration
    In the expression: liftST (getNumElements arr)
    In an equation for ‘getNumElements’:
        getNumElements arr = liftST (getNumElements arr)
    In the instance declaration for ‘MArray (STArray s) e (STT s m)’
...
```

### PR DESCRIPTION
**Pull request by asr**
This PR fix #6.

### CODE REVIEW

**Comment by josefs** [comment]
Thanks!

**Comment by asr** [comment]
Thanks for merging! Could you release to Hackage a new version including this commit, please.

**Comment by josefs** [comment]
Done. Thanks again for your suggestions. I was pleased to learn that Agda uses this library :-)

**Comment by asr** [comment]
Thanks for releasing.

Agda indirectly uses STMonadTrans: Agda depends on the [equivalence](http://hackage.haskell.org/package/equivalence)  library which depend on STMonadTrans.

**Pull request merged**
