### PR TITLE
0.4.5

### PR DESCRIPTION
**Pull request by josefs**
I'd like to make a new release which relaxes the dependency on tasty for upcoming stackage releases. See:
https://github.com/commercialhaskell/stackage/issues/5570
https://github.com/commercialhaskell/stackage/issues/5795

### CODE REVIEW

**Review by andreasabel — APPROVED** [review]
I don't have much to say.  LGTM.

**Comment by andreasabel** [comment]
I added CI on Github Actions using haskell-ci.  Seems like 7.8.4 compilation is broken:
```
rejecting: transformers-0.3.0.0/installed-6458c21515cab7c1cf21e53141557a1c (conflict: STMonadTrans *test => transformers>=0.4 && <0.6)
```
Do we need to involve https://github.com/ekmett/transformers-compat/ ?

**Comment by josefs** [comment]
Thanks for adding the github actions. I fixed the 7.8.3 build by relaxing some constraints.

**Comment by andreasabel** [comment]
Excellent!

**Comment by josefs** [comment]
For the record, I've uploaded 0.4.5 to hackage: 
https://hackage.haskell.org/package/STMonadTrans-0.4.5

**Pull request merged**
